name: Cavoke
on:
  push:
    branches:
      master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Dist
        run: cp -r src dist # TODO: advanced build
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ${{ github.workspace }}/dist
  ssh-deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - name: Install dependencies
        run: |
          sudo apt-get update -yqq
          sudo apt-get install sshpass pptpd -y
      - name: Download and Install NetExtender
        run: |
          wget ${{ env.NETEXTENDER_URL }}
          tar xzvf *.tgz
          cd netExtenderClient
          sudo ./install <<< "y\n"
      - name: Connect to VPN
        run: |
          netExtender -u ${{ secrets.VPN_USERNAME }} -p ${{ secrets.VPN_PASSWORD }} -d ${{ env.VPN_DOMAIN }} ${{ env.VPN_SERVER_URL }} &
          sleep 15
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh ${{ secrets.SSH_USERNAME }}@${{ env.SSH_SERVER_URL }} 'rm ~/public_html/*'
          sshpass -p ${{ secrets.SSH_PASSWORD }} scp -r dist/* ${{ secrets.SSH_USERNAME }}@${{ env.SSH_SERVER_URL }}:~/public_html

env:
  NETEXTENDER_URL: https://software.sonicwall.com/NetExtender/NetExtender.Linux-10.2.845.x86_64.tgz
  VPN_DOMAIN: jacobs
  VPN_SERVER_URL: sma.jacobs-university.de
  SSH_SERVER_URL: clabsql.clamv.jacobs-university.de
